In [1]:
import pandas as pd
import numpy as np

## Load the original file

In [2]:
# Read the raw data
data0 = pd.read_csv('../data/data0.csv')
data0

,文件名,顺序,Eye study,语言,省份,省份.1,省份4分 1=high；2=Upper-middle；3=lower-middle; 4= low,省份3分 1=high；2=middle；3=low,省份3分 1=high；2=middle；3=low(修改四川安徽）,随访,...,10-12年级城市近视人数,10-12年级城市近视率,10-12年级农村人数,10-12年级农村近视人数,10-12年级农村近视率,同年同省小学生人口数,同年同省初中人口数,同年同省小学初中人口总数,离群,备注
0,Chunfeng Zhang 2022,1.0,NaN,0,33,浙江,1,1,1,2,...,\,\,\,\,\,3727273.0,1636425.0,5363698.0,NaN,NaN
1,Dandan Jiang 2021,2.0,NaN,0,33,浙江,1,1,1,1,...,\,NaN,\,\,NaN,3467269.0,1492985.0,4960254.0,NaN,NaN
2,Dandan Jiang 2021,3.0,NaN,0,33,浙江,1,1,1,1,...,\,NaN,\,\,NaN,3569926.0,1479353.0,5049279.0,NaN,2.5年以后，不完全是4-6年级
3,Danjie Jiang 2022,5.0,NaN,0,33,浙江,1,1,1,0,...,969,89.72%,0,0,NaN,3671067.0,1636986.0,5308053.0,NaN,小学段年龄分层根据中文文章：浙江省宁波市 4～6 年级小学生近视现况及其影响因素分析（通过调...
4,Hongyan Chen 2022,7.0,NaN,0,32,江苏,1,1,1,2,...,7173,89.01%,0,0,NaN,5726376.0,2424561.0,8150937.0,NaN,附表1中提供了原始数据，但里面的数据和原文汇报的无法对应，目前按照原始数据结果填写
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,体质健康2019,NaN,体质健康测试,1,51,四川,4,3,2,2,...,744,87.02%,859,735,85.56%,NaN,NaN,NaN,NaN,NaN
433,体质健康2019,NaN,体质健康测试,1,52,贵州,4,3,3,2,...,658,73.19%,889,673,75.70%,NaN,NaN,NaN,NaN,NaN
434,体质健康2019,NaN,体质健康测试,1,53,云南,4,3,3,2,...,915,91.59%,990,798,80.61%,NaN,NaN,NaN,NaN,NaN
435,体质健康2019,NaN,体质健康测试,1,62,甘肃,4,3,3,2,...,809,92.46%,900,740,82.22%,NaN,NaN,NaN,NaN,NaN
436,体质健康2019,NaN,体质健康测试,1,63,青海,4,3,3,2,...,412,87.47%,615,457,74.31%,NaN,NaN,NaN,NaN,NaN

In [3]:
# 2019 data was not marked. Let's assume they are usable with "体质健康测试"
data0['0：不可用；1：可用；2潜力，需整体近视率补充数据；3潜力，需补充整体城乡数据'] = data0['0：不可用；1：可用；2潜力，需整体近视率补充数据；3潜力，需补充整体城乡数据'].fillna(1)

In [4]:
data0

,文件名,顺序,Eye study,语言,省份,省份.1,省份4分 1=high；2=Upper-middle；3=lower-middle; 4= low,省份3分 1=high；2=middle；3=low,省份3分 1=high；2=middle；3=low(修改四川安徽）,随访,...,10-12年级城市近视人数,10-12年级城市近视率,10-12年级农村人数,10-12年级农村近视人数,10-12年级农村近视率,同年同省小学生人口数,同年同省初中人口数,同年同省小学初中人口总数,离群,备注
0,Chunfeng Zhang 2022,1.0,NaN,0,33,浙江,1,1,1,2,...,\,\,\,\,\,3727273.0,1636425.0,5363698.0,NaN,NaN
1,Dandan Jiang 2021,2.0,NaN,0,33,浙江,1,1,1,1,...,\,NaN,\,\,NaN,3467269.0,1492985.0,4960254.0,NaN,NaN
2,Dandan Jiang 2021,3.0,NaN,0,33,浙江,1,1,1,1,...,\,NaN,\,\,NaN,3569926.0,1479353.0,5049279.0,NaN,2.5年以后，不完全是4-6年级
3,Danjie Jiang 2022,5.0,NaN,0,33,浙江,1,1,1,0,...,969,89.72%,0,0,NaN,3671067.0,1636986.0,5308053.0,NaN,小学段年龄分层根据中文文章：浙江省宁波市 4～6 年级小学生近视现况及其影响因素分析（通过调...
4,Hongyan Chen 2022,7.0,NaN,0,32,江苏,1,1,1,2,...,7173,89.01%,0,0,NaN,5726376.0,2424561.0,8150937.0,NaN,附表1中提供了原始数据，但里面的数据和原文汇报的无法对应，目前按照原始数据结果填写
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,体质健康2019,NaN,体质健康测试,1,51,四川,4,3,2,2,...,744,87.02%,859,735,85.56%,NaN,NaN,NaN,NaN,NaN
433,体质健康2019,NaN,体质健康测试,1,52,贵州,4,3,3,2,...,658,73.19%,889,673,75.70%,NaN,NaN,NaN,NaN,NaN
434,体质健康2019,NaN,体质健康测试,1,53,云南,4,3,3,2,...,915,91.59%,990,798,80.61%,NaN,NaN,NaN,NaN,NaN
435,体质健康2019,NaN,体质健康测试,1,62,甘肃,4,3,3,2,...,809,92.46%,900,740,82.22%,NaN,NaN,NaN,NaN,NaN
436,体质健康2019,NaN,体质健康测试,1,63,青海,4,3,3,2,...,412,87.47%,615,457,74.31%,NaN,NaN,NaN,NaN,NaN

In [5]:
province_mapping = {
    '北京': 'Beijing',
    '天津': 'Tianjin',
    '河北': 'Hebei',
    '山西': 'Shanxi',
    '内蒙古': 'Inner Mongolia',
    '内蒙': 'Inner Mongolia',
    '辽宁': 'Liaoning',
    '吉林': 'Jilin',
    '黑龙江': 'Heilongjiang',
    '上海': 'Shanghai',
    '江苏': 'Jiangsu',
    '浙江': 'Zhejiang',
    '安徽': 'Anhui',
    '福建': 'Fujian',
    '江西': 'Jiangxi',
    '山东': 'Shandong',
    '河南': 'Henan',
    '湖北': 'Hubei',
    '湖南': 'Hunan',
    '广东': 'Guangdong',
    '广西': 'Guangxi',
    '海南': 'Hainan',
    '重庆': 'Chongqing',
    '四川': 'Sichuan',
    '贵州': 'Guizhou',
    '云南': 'Yunnan',
    '西藏': 'Tibet',
    '陕西': 'Shaanxi',
    '甘肃': 'Gansu',
    '青海': 'Qinghai',
    '宁夏': 'Ningxia',
    '新疆': 'Xinjiang',
    '台湾': 'Taiwan',
    '香港': 'Hong Kong',
    '澳门': 'Macao'
}
data0['英文省份'] = data0['省份.1'].map(province_mapping)

In [6]:
# 筛选可用数据, we use all usable data marked with 1.
df0 = data0[(data0['0：不可用；1：可用；2潜力，需整体近视率补充数据；3潜力，需补充整体城乡数据']==1)]
df0

,文件名,顺序,Eye study,语言,省份,省份.1,省份4分 1=high；2=Upper-middle；3=lower-middle; 4= low,省份3分 1=high；2=middle；3=low,省份3分 1=high；2=middle；3=low(修改四川安徽）,随访,...,10-12年级城市近视率,10-12年级农村人数,10-12年级农村近视人数,10-12年级农村近视率,同年同省小学生人口数,同年同省初中人口数,同年同省小学初中人口总数,离群,备注,英文省份
1,Dandan Jiang 2021,2.0,NaN,0,33,浙江,1,1,1,1,...,NaN,\,\,NaN,3467269.0,1492985.0,4960254.0,NaN,NaN,Zhejiang
2,Dandan Jiang 2021,3.0,NaN,0,33,浙江,1,1,1,1,...,NaN,\,\,NaN,3569926.0,1479353.0,5049279.0,NaN,2.5年以后，不完全是4-6年级,Zhejiang
3,Danjie Jiang 2022,5.0,NaN,0,33,浙江,1,1,1,0,...,89.72%,0,0,NaN,3671067.0,1636986.0,5308053.0,NaN,小学段年龄分层根据中文文章：浙江省宁波市 4～6 年级小学生近视现况及其影响因素分析（通过调...,Zhejiang
4,Hongyan Chen 2022,7.0,NaN,0,32,江苏,1,1,1,2,...,89.01%,0,0,NaN,5726376.0,2424561.0,8150937.0,NaN,附表1中提供了原始数据，但里面的数据和原文汇报的无法对应，目前按照原始数据结果填写,Jiangsu
5,Hongyan Chen 2022,8.0,NaN,0,32,江苏,1,1,1,2,...,91.37%,0,0,NaN,5808208.0,2542608.0,8350816.0,NaN,附表1中提供了原始数据，但里面的数据和原文汇报的无法对应，目前按照原始数据情况填写,Jiangsu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,体质健康2019,NaN,体质健康测试,1,51,四川,4,3,2,2,...,87.02%,859,735,85.56%,NaN,NaN,NaN,NaN,NaN,Sichuan
433,体质健康2019,NaN,体质健康测试,1,52,贵州,4,3,3,2,...,73.19%,889,673,75.70%,NaN,NaN,NaN,NaN,NaN,Guizhou
434,体质健康2019,NaN,体质健康测试,1,53,云南,4,3,3,2,...,91.59%,990,798,80.61%,NaN,NaN,NaN,NaN,NaN,Yunnan
435,体质健康2019,NaN,体质健康测试,1,62,甘肃,4,3,3,2,...,92.46%,900,740,82.22%,NaN,NaN,NaN,NaN,NaN,Gansu
436,体质健康2019,NaN,体质健康测试,1,63,青海,4,3,3,2,...,87.47%,615,457,74.31%,NaN,NaN,NaN,NaN,NaN,Qinghai

In [7]:
# Select urban and rual data
df = df0.iloc[:, [80,14,16,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74]]
df

,英文省份,年份,验光方式1非散瞳；2散瞳；3试片,1-3年级城市人数,1-3年级城市近视人数,1-3年级城市患病率,1-3年级农村人数,1-3年级农村近视人数,1-3年级农村患病率,4-6年级城市人数,...,7-9年级城市近视率,7-9年级农村人数,7-9年级农村近视人数,7-9年级农村近视率,10-12年级城市人数,10-12年级城市近视人数,10-12年级城市近视率,10-12年级农村人数,10-12年级农村近视人数,10-12年级农村近视率
1,Zhejiang,2012.0,1.0,1294,184,14.22%,0,0,NaN,\,...,NaN,\,\,NaN,\,\,NaN,\,\,NaN
2,Zhejiang,2015.0,1.0,\,\,NaN,\,\,NaN,1294,...,NaN,\,\,NaN,\,\,NaN,\,\,NaN
3,Zhejiang,2019.0,1.0,\,\,NaN,\,\,NaN,1088,...,81.43%,0,0,NaN,1080,969,89.72%,0,0,NaN
4,Jiangsu,2019.0,1.0,20735,4246,20.48%,20545,2924,14.23%,20124,...,85.04%,14471,8551,59.09%,8059,7173,89.01%,0,0,NaN
5,Jiangsu,2020.0,1.0,21052,5445,25.86%,18677,3582,19.18%,22386,...,87.69%,14366,9342,65.03%,9347,8540,91.37%,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,Sichuan,2019.0,3.0,924,270,29.22%,976,225,23.05%,988,...,63.56%,918,507,55.23%,855,744,87.02%,859,735,85.56%
433,Guizhou,2019.0,3.0,896,201,22.43%,851,173,20.33%,896,...,48.33%,898,336,37.42%,899,658,73.19%,889,673,75.70%
434,Yunnan,2019.0,3.0,995,267,26.83%,1005,227,22.59%,1008,...,62.60%,1004,565,56.27%,999,915,91.59%,990,798,80.61%
435,Gansu,2019.0,3.0,678,221,32.60%,922,190,20.61%,897,...,60.76%,883,449,50.85%,875,809,92.46%,900,740,82.22%
436,Qinghai,NaN,NaN,914,264,28.88%,618,124,20.06%,915,...,58.14%,597,221,37.02%,471,412,87.47%,615,457,74.31%

In [8]:
# Mark all "\" and "0" as nan
df = df.replace('\\', np.nan)
df = df.replace(str(0), np.nan)

# Remove % to demimals
for j in range(5, 28, 3):
    df.iloc[:,j] = df.iloc[:,j].str.rstrip('%').astype(float) / 100
    
df

,英文省份,年份,验光方式1非散瞳；2散瞳；3试片,1-3年级城市人数,1-3年级城市近视人数,1-3年级城市患病率,1-3年级农村人数,1-3年级农村近视人数,1-3年级农村患病率,4-6年级城市人数,...,7-9年级城市近视率,7-9年级农村人数,7-9年级农村近视人数,7-9年级农村近视率,10-12年级城市人数,10-12年级城市近视人数,10-12年级城市近视率,10-12年级农村人数,10-12年级农村近视人数,10-12年级农村近视率
1,Zhejiang,2012.0,1.0,1294,184,0.1422,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zhejiang,2015.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Zhejiang,2019.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1088,...,0.8143,0,0,NaN,1080,969,0.8972,0,0,NaN
4,Jiangsu,2019.0,1.0,20735,4246,0.2048,20545,2924,0.1423,20124,...,0.8504,14471,8551,0.5909,8059,7173,0.8901,0,0,NaN
5,Jiangsu,2020.0,1.0,21052,5445,0.2586,18677,3582,0.1918,22386,...,0.8769,14366,9342,0.6503,9347,8540,0.9137,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,Sichuan,2019.0,3.0,924,270,0.2922,976,225,0.2305,988,...,0.6356,918,507,0.5523,855,744,0.8702,859,735,0.8556
433,Guizhou,2019.0,3.0,896,201,0.2243,851,173,0.2033,896,...,0.4833,898,336,0.3742,899,658,0.7319,889,673,0.757
434,Yunnan,2019.0,3.0,995,267,0.2683,1005,227,0.2259,1008,...,0.626,1004,565,0.5627,999,915,0.9159,990,798,0.8061
435,Gansu,2019.0,3.0,678,221,0.326,922,190,0.2061,897,...,0.6076,883,449,0.5085,875,809,0.9246,900,740,0.8222
436,Qinghai,NaN,NaN,914,264,0.2888,618,124,0.2006,915,...,0.5814,597,221,0.3702,471,412,0.8747,615,457,0.7431

In [9]:
# 验光方式: 2散瞳, 更精准，应该赋予更高的权重
df_cycloplegia = df[df['验光方式1非散瞳；2散瞳；3试片']==2]
df_cycloplegia

,英文省份,年份,验光方式1非散瞳；2散瞳；3试片,1-3年级城市人数,1-3年级城市近视人数,1-3年级城市患病率,1-3年级农村人数,1-3年级农村近视人数,1-3年级农村患病率,4-6年级城市人数,...,7-9年级城市近视率,7-9年级农村人数,7-9年级农村近视人数,7-9年级农村近视率,10-12年级城市人数,10-12年级城市近视人数,10-12年级城市近视率,10-12年级农村人数,10-12年级农村近视人数,10-12年级农村近视率
6,Beijing,2000.0,2.0,0,0,NaN,1043,80,0.0767,NaN,...,NaN,2986,815,0.2731,0,0,NaN,944,447,0.4734
7,Beijing,1998.0,2.0,0,0,NaN,1808,98,0.0542,0,...,NaN,1432,516,0.3603,NaN,NaN,NaN,NaN,NaN,NaN
8,Shandong,2012.0,2.0,974,244,0.2505,963,126,0.1308,874,...,0.8178,561,317,0.5651,129,124,0.9612,244,186,0.7623
17,Shandong,2015.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1368,...,0.615,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Guangdong,2014.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,Qinghai,2019.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,Yunnan,2017.0,2.0,0,0,NaN,2903,53,0.0183,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
368,Tibet,2020.0,2.0,1819,199,0.1094,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,Gansu,2004.0,2.0,0,0,NaN,18362,1038,0.0565,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
370,Gansu,2002.0,2.0,0,0,NaN,2697,156,0.0578,0,...,NaN,480,159,0.3313,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# 验光方式: 1,3非散瞳，有一定的偏差，但是整体趋势具有建模意义。
df_nocycloplegia = df[(df['验光方式1非散瞳；2散瞳；3试片']==1) | (df['验光方式1非散瞳；2散瞳；3试片']==3)]
df_nocycloplegia

,英文省份,年份,验光方式1非散瞳；2散瞳；3试片,1-3年级城市人数,1-3年级城市近视人数,1-3年级城市患病率,1-3年级农村人数,1-3年级农村近视人数,1-3年级农村患病率,4-6年级城市人数,...,7-9年级城市近视率,7-9年级农村人数,7-9年级农村近视人数,7-9年级农村近视率,10-12年级城市人数,10-12年级城市近视人数,10-12年级城市近视率,10-12年级农村人数,10-12年级农村近视人数,10-12年级农村近视率
1,Zhejiang,2012.0,1.0,1294,184,0.1422,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zhejiang,2015.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Zhejiang,2019.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1088,...,0.8143,0,0,NaN,1080,969,0.8972,0,0,NaN
4,Jiangsu,2019.0,1.0,20735,4246,0.2048,20545,2924,0.1423,20124,...,0.8504,14471,8551,0.5909,8059,7173,0.8901,0,0,NaN
5,Jiangsu,2020.0,1.0,21052,5445,0.2586,18677,3582,0.1918,22386,...,0.8769,14366,9342,0.6503,9347,8540,0.9137,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,Guangxi,2019.0,3.0,896,230,0.2567,839,171,0.2038,890,...,0.5865,891,353,0.3962,760,626,0.8237,897,757,0.8439
432,Sichuan,2019.0,3.0,924,270,0.2922,976,225,0.2305,988,...,0.6356,918,507,0.5523,855,744,0.8702,859,735,0.8556
433,Guizhou,2019.0,3.0,896,201,0.2243,851,173,0.2033,896,...,0.4833,898,336,0.3742,899,658,0.7319,889,673,0.757
434,Yunnan,2019.0,3.0,995,267,0.2683,1005,227,0.2259,1008,...,0.626,1004,565,0.5627,999,915,0.9159,990,798,0.8061
435,Gansu,2019.0,3.0,678,221,0.326,922,190,0.2061,897,...,0.6076,883,449,0.5085,875,809,0.9246,900,740,0.8222

In [11]:
# Saving filtered data
df.to_csv('filtered_data.csv', index=False)
df_cycloplegia.to_csv('filtered_data_cycloplegia.csv', index=False)
df_nocycloplegia.to_csv('filtered_data_nocycloplegia.csv', index=False)

In [12]:
data=pd.read_csv('filtered_data.csv')
data

,英文省份,年份,验光方式1非散瞳；2散瞳；3试片,1-3年级城市人数,1-3年级城市近视人数,1-3年级城市患病率,1-3年级农村人数,1-3年级农村近视人数,1-3年级农村患病率,4-6年级城市人数,...,7-9年级城市近视率,7-9年级农村人数,7-9年级农村近视人数,7-9年级农村近视率,10-12年级城市人数,10-12年级城市近视人数,10-12年级城市近视率,10-12年级农村人数,10-12年级农村近视人数,10-12年级农村近视率
0,Zhejiang,2012.0,1.0,1294.0,184.0,0.1422,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Zhejiang,2015.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1294.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zhejiang,2019.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1088.0,...,0.8143,0.0,0.0,NaN,1080.0,969.0,0.8972,0.0,0.0,NaN
3,Jiangsu,2019.0,1.0,20735.0,4246.0,0.2048,20545.0,2924.0,0.1423,20124.0,...,0.8504,14471.0,8551.0,0.5909,8059.0,7173.0,0.8901,0.0,0.0,NaN
4,Jiangsu,2020.0,1.0,21052.0,5445.0,0.2586,18677.0,3582.0,0.1918,22386.0,...,0.8769,14366.0,9342.0,0.6503,9347.0,8540.0,0.9137,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,Sichuan,2019.0,3.0,924.0,270.0,0.2922,976.0,225.0,0.2305,988.0,...,0.6356,918.0,507.0,0.5523,855.0,744.0,0.8702,859.0,735.0,0.8556
373,Guizhou,2019.0,3.0,896.0,201.0,0.2243,851.0,173.0,0.2033,896.0,...,0.4833,898.0,336.0,0.3742,899.0,658.0,0.7319,889.0,673.0,0.7570
374,Yunnan,2019.0,3.0,995.0,267.0,0.2683,1005.0,227.0,0.2259,1008.0,...,0.6260,1004.0,565.0,0.5627,999.0,915.0,0.9159,990.0,798.0,0.8061
375,Gansu,2019.0,3.0,678.0,221.0,0.3260,922.0,190.0,0.2061,897.0,...,0.6076,883.0,449.0,0.5085,875.0,809.0,0.9246,900.0,740.0,0.8222
376,Qinghai,NaN,NaN,914.0,264.0,0.2888,618.0,124.0,0.2006,915.0,...,0.5814,597.0,221.0,0.3702,471.0,412.0,0.8747,615.0,457.0,0.7431

In [13]:
empty = pd.read_csv('empty table.csv')
empty['method_1'] = np.nan
empty

,province,year,age_group,method,population_urban,myopia_urban,myopia_rate_urban,population_rural,myopia_rural,myopia_rate_rural,method.1,number of junior secondary school graduates,New Student Enrollment in high school,articulation rate,GDP,method_1
0,Anhui,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chongqing,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gansu,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,Tianjin,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3096,Tibet,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3097,Xinjiang,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3098,Yunnan,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3099,Zhejiang,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# 填充 method 2 散瞳, 更精准，应该赋予更高的权重

data_2 = data[(data['验光方式1非散瞳；2散瞳；3试片']==2)]
grouped_data = data_2.groupby(['英文省份', '年份'])
for group_name, group_data in grouped_data:
    province, year = group_name
    method = 2
    value = []
    for j in range(5, 28, 3):
        group_data_0 = group_data.iloc[:, j]
        # group_data_0 = group_data.iloc[:, j].fillna('NaN')
        # group_data_1 = group_data_0.str.rstrip('%').astype(float) / 100
        mean = group_data_0.mean()
        value.append(mean)
    
    for i in range(1, 5):
        empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'method']=method
        empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'method_1']=method
        empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'myopia_rate_urban'] = value[2*i-2]
        empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'myopia_rate_rural'] = value[2*i-1]

    
empty

,province,year,age_group,method,population_urban,myopia_urban,myopia_rate_urban,population_rural,myopia_rural,myopia_rate_rural,method.1,number of junior secondary school graduates,New Student Enrollment in high school,articulation rate,GDP,method_1
0,Anhui,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,1998,1,2.0,NaN,NaN,NaN,NaN,NaN,0.0542,NaN,NaN,NaN,NaN,NaN,2.0
2,Chongqing,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,1998,1,2.0,NaN,NaN,0.1793,NaN,NaN,0.0758,NaN,NaN,NaN,NaN,NaN,2.0
4,Gansu,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,Tianjin,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3096,Tibet,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3097,Xinjiang,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3098,Yunnan,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3099,Zhejiang,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Remove suspicious inputed data for certain age group and province
empty.loc[(empty['year'] == 2019) & (empty['province'] == 'Xinjiang') & (empty['age_group'] == 3), 'myopia_rate_urban'] = np.nan
empty.loc[(empty['year'] == 2019) & (empty['province'] == 'Xinjiang') & (empty['age_group'] == 3), 'method']=np.nan

In [16]:
empty_cycloplegia = empty
empty_cycloplegia.to_csv('filled_cycloplegia.csv', index=False)

In [17]:
# Read the estimated mean difference for calibration
# Run "Myopia_cycloplegia_diff.R" file to obtain the mean difference.

meandiff_cycloplegia_urban = pd.read_csv('../meandiff_cycloplegia_urban_4groups.csv')
meandiff_cycloplegia_rural = pd.read_csv('../meandiff_cycloplegia_rural_4groups.csv')

meansum_cycloplegia_urban = pd.read_csv('../meansum_cycloplegia_urban_4groups.csv')
meansum_cycloplegia_rural = pd.read_csv('../meansum_cycloplegia_rural_4groups.csv')

In [18]:
weight_cycloplegia_urban = (2*abs(meandiff_cycloplegia_urban.iloc[:,1:])/meansum_cycloplegia_urban.iloc[:, 1:]).mean()
weight_cycloplegia_rural = (2*abs(meandiff_cycloplegia_rural.iloc[:,1:])/meansum_cycloplegia_rural.iloc[:, 1:]).mean()
weight_cycloplegia_rural = [0.95, 0.5, 0.95, 0.5] # 
# weight_cycloplegia_urban['year'] = meansum_cycloplegia_urban['year']
# weight_cycloplegia_rural['year'] = meansum_cycloplegia_rural['year']
weight_cycloplegia = (weight_cycloplegia_urban+weight_cycloplegia_rural)/2

In [19]:
weight_cycloplegia_rural

[0.95, 0.5, 0.95, 0.5]

In [20]:
# 填充 method 1 和 3

# Fill and calibration
data_1 = data[(data['验光方式1非散瞳；2散瞳；3试片']==1) | (data['验光方式1非散瞳；2散瞳；3试片']==3)]
grouped_data = data_1.groupby(['英文省份', '年份'])
for group_name, group_data in grouped_data:
    province, year = group_name
    method = '1 or 3'
    value = []
    
    # change 100% to numbers 
    for j in range(5, 28, 3):
        group_data_0 = group_data.iloc[:, j]
        # group_data_0 = group_data.iloc[:, j].fillna('NaN')
        # group_data_1 = group_data_0.str.rstrip('%').astype(float) / 100
        mean = group_data_0.mean()
        value.append(mean)

    # Justify by the estimated difference between cycloplegia and nocycloplegia
    
    for i in range(1, 5):   
        value_orig = value[2*i-2] # orginal value to be used
        
        if empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'myopia_rate_urban'].isna().any():
            empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'method'] = method

            weight = weight_cycloplegia_urban.iloc[i-1]
            value_calibrate = meandiff_cycloplegia_urban.loc[(meandiff_cycloplegia_urban.year==year),"g"+str(i)].values*weight
            value_final = value_orig + value_calibrate
            empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'myopia_rate_urban'] = value_final
        
        if empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'myopia_rate_rural'].isna().any():
            empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'method_1']=method

            weight = weight_cycloplegia_rural[i-1]
            value_calibrate = meandiff_cycloplegia_rural.loc[(meandiff_cycloplegia_rural.year==year),"g"+str(i)].values*weight
            value_final = value_orig + value_calibrate
            empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'myopia_rate_rural'] = value_final
empty

/tmp/ipykernel_514853/1375922237.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1 or 3' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'method'] = method
/tmp/ipykernel_514853/1375922237.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1 or 3' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  empty.loc[(empty['province'] == province) & (empty['year'] == year) & (empty['age_group'] == i), 'method_1']=method

,province,year,age_group,method,population_urban,myopia_urban,myopia_rate_urban,population_rural,myopia_rural,myopia_rate_rural,method.1,number of junior secondary school graduates,New Student Enrollment in high school,articulation rate,GDP,method_1
0,Anhui,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,1998,1,2.0,NaN,NaN,NaN,NaN,NaN,0.054200,NaN,NaN,NaN,NaN,NaN,2.0
2,Chongqing,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,1998,1,2.0,NaN,NaN,0.179300,NaN,NaN,0.075800,NaN,NaN,NaN,NaN,NaN,2.0
4,Gansu,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,Tianjin,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3096,Tibet,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3097,Xinjiang,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3098,Yunnan,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3099,Zhejiang,2022,4,1 or 3,NaN,NaN,0.843609,NaN,NaN,0.791249,NaN,NaN,NaN,NaN,NaN,1 or 3

In [21]:
empty.to_csv('empty2.csv', index=False)

In [22]:
empty

,province,year,age_group,method,population_urban,myopia_urban,myopia_rate_urban,population_rural,myopia_rural,myopia_rate_rural,method.1,number of junior secondary school graduates,New Student Enrollment in high school,articulation rate,GDP,method_1
0,Anhui,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,1998,1,2.0,NaN,NaN,NaN,NaN,NaN,0.054200,NaN,NaN,NaN,NaN,NaN,2.0
2,Chongqing,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,1998,1,2.0,NaN,NaN,0.179300,NaN,NaN,0.075800,NaN,NaN,NaN,NaN,NaN,2.0
4,Gansu,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,Tianjin,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3096,Tibet,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3097,Xinjiang,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3098,Yunnan,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3099,Zhejiang,2022,4,1 or 3,NaN,NaN,0.843609,NaN,NaN,0.791249,NaN,NaN,NaN,NaN,NaN,1 or 3

In [23]:
empty_sorted = empty.sort_values(by=['year', 'age_group'])

# Remove suspicious inputed data for certain age group and province

empty_sorted.loc[(empty_sorted['year'] == 2006) & (empty_sorted['province'] == 'Chongqing') & (empty_sorted['age_group'] == 3), 'myopia_rate_urban'] = np.nan
empty_sorted.loc[(empty_sorted['year'] == 2020) & (empty_sorted['province'] == 'Inner Mongolia') & (empty_sorted['age_group'] == 3), 'myopia_rate_rural'] = np.nan
empty_sorted.loc[(empty_sorted['year'] == 2020) & (empty_sorted['province'] == 'Inner Mongolia') & (empty_sorted['age_group'] == 4), 'myopia_rate_rural'] = np.nan
empty_sorted.loc[(empty_sorted['year'] == 2020) & (empty_sorted['province'] == 'Guangxi') & (empty_sorted['age_group'] == 4), 'myopia_rate_rural'] = np.nan
empty_sorted.loc[(empty_sorted['year'] == 2015) & (empty_sorted['age_group'] == 2), 'myopia_rate_urban'] = np.nan
empty_sorted.loc[(empty_sorted['year'] == 2019) & (empty_sorted['age_group'] == 4), 'myopia_rate_urban'] = np.nan

empty_sorted.to_csv('empty_sorted.csv', index=False)

In [24]:
empty_sorted=pd.read_csv('empty_sorted.csv')

filled = empty_sorted.copy()
filled

,province,year,age_group,method,population_urban,myopia_urban,myopia_rate_urban,population_rural,myopia_rural,myopia_rate_rural,method.1,number of junior secondary school graduates,New Student Enrollment in high school,articulation rate,GDP,method_1
0,Anhui,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,1998,1,2.0,NaN,NaN,NaN,NaN,NaN,0.054200,NaN,NaN,NaN,NaN,NaN,2.0
2,Chongqing,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,1998,1,2.0,NaN,NaN,0.179300,NaN,NaN,0.075800,NaN,NaN,NaN,NaN,NaN,2.0
4,Gansu,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,Tianjin,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3096,Tibet,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3097,Xinjiang,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3098,Yunnan,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3099,Zhejiang,2022,4,1 or 3,NaN,NaN,0.843609,NaN,NaN,0.791249,NaN,NaN,NaN,NaN,NaN,1 or 3

In [25]:
# Using "geo distance" as distance fur urban and rural rate

distance = pd.read_csv('../data/weight/province_distance_matrix.csv')
distance['province0'] = distance['省份'].map(province_mapping)
distance

for i in range(0,2852):
    nearest_row_index = np.nan
    if pd.isna(empty_sorted.loc[i, 'myopia_rate_urban']):
        year = empty_sorted.loc[i,'year']
        age_group = empty_sorted.loc[i,'age_group']
        try:
            index_lst = empty_sorted[(empty_sorted['year'] == year) & (empty_sorted['age_group'] == age_group) & (empty_sorted['myopia_rate_urban'].notnull())].index.to_list()
            if len(index_lst)!=0:
                nearest_index = min(range(len(index_lst)), key=lambda j: abs(index_lst[j] - i))
                nearest_row_index = index_lst[nearest_index]
                if abs(nearest_row_index - i)  < 3:
                    filled.loc[i,'myopia_rate_urban']=empty_sorted.loc[nearest_row_index,'myopia_rate_urban']
                    filled.loc[i,'method'] = 4
        except IndexError:
            pass

    if pd.isna(empty_sorted.loc[i, 'myopia_rate_rural']):
        year = empty_sorted.loc[i,'year']
        age_group = empty_sorted.loc[i,'age_group']
        try:
            index_lst = empty_sorted[(empty_sorted['year'] == year) & (empty_sorted['age_group'] == age_group) & (empty_sorted['myopia_rate_rural'].notnull())].index.to_list()
            if len(index_lst)!=0:
                nearest_index = min(range(len(index_lst)), key=lambda j: abs(index_lst[j] - i))
                nearest_row_index = index_lst[nearest_index]
                if abs(nearest_row_index - i) < 3:
                    filled.loc[i,'myopia_rate_rural']=empty_sorted.loc[nearest_row_index,'myopia_rate_rural']
                    filled.loc[i,'method_1'] = 4
        except IndexError:
            pass
        
filled

,province,year,age_group,method,population_urban,myopia_urban,myopia_rate_urban,population_rural,myopia_rural,myopia_rate_rural,method.1,number of junior secondary school graduates,New Student Enrollment in high school,articulation rate,GDP,method_1
0,Anhui,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,0.054200,NaN,NaN,NaN,NaN,NaN,4
1,Beijing,1998,1,4,NaN,NaN,0.179300,NaN,NaN,0.054200,NaN,NaN,NaN,NaN,NaN,2.0
2,Chongqing,1998,1,4,NaN,NaN,0.179300,NaN,NaN,0.054200,NaN,NaN,NaN,NaN,NaN,4
3,Fujian,1998,1,2.0,NaN,NaN,0.179300,NaN,NaN,0.075800,NaN,NaN,NaN,NaN,NaN,2.0
4,Gansu,1998,1,4,NaN,NaN,0.179300,NaN,NaN,0.075800,NaN,NaN,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,Tianjin,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3096,Tibet,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3097,Xinjiang,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3098,Yunnan,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3099,Zhejiang,2022,4,1 or 3,NaN,NaN,0.843609,NaN,NaN,0.791249,NaN,NaN,NaN,NaN,NaN,1 or 3

In [26]:
# Using "Sunlight Intensity" as distance fur urban and rural rate

rank = pd.read_csv('../data/weight/sunshine-hours-rank.csv')
rank['province0'] = rank['province'].map(province_mapping)

for i in range(0,2852):
    nearest_row_index = np.nan
    if pd.isna(empty_sorted.loc[i, 'myopia_rate_urban']):
        year = empty_sorted.loc[i,'year']
        age_group = empty_sorted.loc[i,'age_group']
        try:
            index_lst = empty_sorted[(empty_sorted['year'] == year) & (empty_sorted['age_group'] == age_group) & (empty_sorted['myopia_rate_urban'].notnull())].index.to_list()
            if len(index_lst)!=0:
                nearest_index = min(range(len(index_lst)), key=lambda j: abs(index_lst[j] - i))
                nearest_row_index = index_lst[nearest_index]
                if abs(nearest_row_index - i)  < 3:
                    filled.loc[i,'myopia_rate_urban']=empty_sorted.loc[nearest_row_index,'myopia_rate_urban']
                    filled.loc[i,'method'] = 4
        except IndexError:
            pass

    if pd.isna(empty_sorted.loc[i, 'myopia_rate_rural']):
        year = empty_sorted.loc[i,'year']
        age_group = empty_sorted.loc[i,'age_group']
        try:
            index_lst = empty_sorted[(empty_sorted['year'] == year) & (empty_sorted['age_group'] == age_group) & (empty_sorted['myopia_rate_rural'].notnull())].index.to_list()
            if len(index_lst)!=0:
                nearest_index = min(range(len(index_lst)), key=lambda j: abs(index_lst[j] - i))
                nearest_row_index = index_lst[nearest_index]
                if abs(nearest_row_index - i) < 3:
                    filled.loc[i,'myopia_rate_rural']=empty_sorted.loc[nearest_row_index,'myopia_rate_rural']
                    filled.loc[i,'method_1'] = 4
        except IndexError:
            pass
        
filled

,province,year,age_group,method,population_urban,myopia_urban,myopia_rate_urban,population_rural,myopia_rural,myopia_rate_rural,method.1,number of junior secondary school graduates,New Student Enrollment in high school,articulation rate,GDP,method_1
0,Anhui,1998,1,NaN,NaN,NaN,NaN,NaN,NaN,0.054200,NaN,NaN,NaN,NaN,NaN,4
1,Beijing,1998,1,4,NaN,NaN,0.179300,NaN,NaN,0.054200,NaN,NaN,NaN,NaN,NaN,2.0
2,Chongqing,1998,1,4,NaN,NaN,0.179300,NaN,NaN,0.054200,NaN,NaN,NaN,NaN,NaN,4
3,Fujian,1998,1,2.0,NaN,NaN,0.179300,NaN,NaN,0.075800,NaN,NaN,NaN,NaN,NaN,2.0
4,Gansu,1998,1,4,NaN,NaN,0.179300,NaN,NaN,0.075800,NaN,NaN,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,Tianjin,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3096,Tibet,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3097,Xinjiang,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3098,Yunnan,2022,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3099,Zhejiang,2022,4,1 or 3,NaN,NaN,0.843609,NaN,NaN,0.791249,NaN,NaN,NaN,NaN,NaN,1 or 3

In [27]:
filled.to_csv('filled_with_basic_methods_and_neighbors.csv', index=False)